// <auto-generated />
namespace CinemaAdmin.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DatabaseUpdate03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseUpdate03));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051527525_DatabaseUpdate0.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
